#!/bin/bash
#SBATCH --job-name=spike_sorting
#SBATCH --partition=gpu2node
#SBATCH --nodelist=gpu01
#SBATCH --cpus-per-task=32
#SBATCH --mem=32G

eval "$(conda shell.bash hook)"
conda activate data-proc

export COMBINATO_PATH=/share/home/mitan/combinato

python3 /share/home/mitan/Cuhksz4090/spike_sorting/align_firing_rate_to_triggers.py \
  --mat session2=/share/workspace3/ieeg/micro/word_boun_perce_v1/bistable_sub4/bistable_sub4_session2 \
  --mat session3=/share/workspace3/ieeg/micro/word_boun_perce_v1/bistable_sub4/bistable_sub4_session3 \
  --mat session5=/share/workspace3/ieeg/micro/word_boun_perce_v1/bistable_sub4/bistable_sub4_session5 \
  --binary-num-channels 128 --binary-sampling-rate 30000 --binary-min-pulse-ms 0.5

# when generating sortingview links without figpack, use the following command:
#python /share/home/mitan/spike_sorting/generate_sortingview_links.py \
#  --mode local \
#  --base-port 50100 \
#  --hold-seconds 14400 #4h

# when generating sortingview links with both local and figpack, first 
# set FIGPACK_API_KEY 
#export FIGPACK_API_KEY=7ca15431465413347d78cc2a08ad1816e127e56dd01e70aff9ef888c7ac9e4ba
# and then use the following command:
#python /share/home/mitan/spike_sorting/generate_sortingview_links.py \
#  --mode local --add-upload-urls \

# api key generated by kachery-cloud Cax4n0VpQHW585RKePvFpcL7O1CXP3oZ
# figpack api key: 7ca15431465413347d78cc2a08ad1816e127e56dd01e70aff9ef888c7ac9e4ba

# when using combinato as the sortor, add 
#export COMBINATO_PATH=/share/home/mitan/combinato
# before python /share/home/mitan/spike_sorting/combinato/spikesort_combinato.py